version: "3.3"
services:
  postgres:
    restart: always
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  formbricks:
    restart: always
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.formbricks.rule=Host(`api.example.com`)" # TODO: Change with your own domain
      - "traefik.http.routers.formbricks.tls.certresolver=default"
      - "traefik.http.routers.formbricks.entrypoints=websecure"
      - "traefik.http.services.formbricks.loadbalancer.server.port=3000"

volumes:
  postgres:
    driver: local
