name: Cron - reportUsageToStripe

on:
  # "Scheduled workflows run on the latest commit on the default or base branch."
  # — https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#schedule
schedule:
  # This will run the job at 23:00 UTC on days 28, 29, 30, and 31 of every month. However, not every month has 31 days,
  # and February can have either 28 or 29 days. GitHub Actions will simply ignore the invalid dates, so the job will only
  # run once on the last day of the month.
  - cron: "0 21 28-31 * *"
jobs:
  cron-reportUsageToStripe:
    env:
      APP_URL: ${{ secrets.APP_URL }}
      API_KEY: ${{ secrets.API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        if: ${{ env.APP_URL && env.API_KEY }}
        run: |
          curl ${{ env.APP_URL }}/api/cron/report-usage \
            -X GET \
            -H 'x-api-key: ${{ env.API_KEY }}' \
            --fail
