name: Cron - reportUsageToStripe

on:
  # "Scheduled workflows run on the latest commit on the default or base branch."
  # — https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#schedule
  schedule:
    # Runs once a week at a specific time (e.g., 08:00 on Monday). Adjust the time as needed.
    - cron: "0 8 * * 1"
jobs:
  cron-reportUsageToStripe:
    env:
      APP_URL: ${{ secrets.APP_URL }}
      API_KEY: ${{ secrets.API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        if: ${{ env.APP_URL && env.API_KEY }}
        run: |
          curl ${{ env.APP_URL }}/api/cron/report-usage \
            -X GET \
            -H 'x-api-key: ${{ env.API_KEY }}' \
            --fail
